version: '2'
services:
    hlyda_bos-app:
        image: hlyda_bos
        external_links:
            - hlyda_bos-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/hlyda_bos?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    hlyda_bos-mysql:
        extends:
            file: mysql.yml
            service: hlyda_bos-mysql
