version: '2'
services:
    hlyda_bos-mysql:
        container_name: hlyda_bos-mysql
        image: mysql:5.7.13
        # volumes:
        #     - ~/volumes/jhipster/hlyda_bos/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=hlyda_bos
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
